In [ ]:
import pandas as pd

df_data = pd.read_csv('../data/raw/insee_data.csv', sep=';')
df_cloud = pd.read_csv('../data/raw/insee_cloud.csv', sep=';')
df_ia = pd.read_csv('../data/raw/insee_ia.csv', sep=';')

,Taille_IR,ACT_IR,NB_ENT,IA_TECH,IA_TECH_TEXMIN,IA_TECH_PAROLE,IA_TECH_GAT,IA_TECH_IMAGES,IA_TECH_AAAD,IA_TECH_DECIS,IA_TECH_MVT,IA_US,IA_US_MARKETING,IA_US_PRODUCT,IA_US_ADMIN,IA_US_LOGISTIQ,IA_US_SECU,IA_US_COMPTA,IA_US_RECHERCHE
0,Ens,Ens,172345,10142,4007,2204,1880,2508,4569,3438,887,7154,1765,2022,1116,351,2216,3096,2375
1,po1,Ens,94858,4004,1685,768,738,918,1396,1201,189,2509,516,711,304,60,598,1118,699
2,po2,Ens,50237,2839,1085,803,524,710,1348,969,247,2001,553,571,381,63,383,913,741
3,po3,Ens,22321,2267,833,364,377,594,1248,778,263,1771,448,444,273,100,669,804,628
4,po4,Ens,4929,1032,404,270,241,286,577,489,189,873,248,296,158,128,566,261,308

In [ ]:
df_data.head()

,Taille_IR,ACT_IR,NB_ENT,IA_TECH,IA_TECH_TEXMIN,IA_TECH_PAROLE,IA_TECH_GAT,IA_TECH_IMAGES,IA_TECH_AAAD,IA_TECH_DECIS,IA_TECH_MVT,IA_US,IA_US_MARKETING,IA_US_PRODUCT,IA_US_ADMIN,IA_US_LOGISTIQ,IA_US_SECU,IA_US_COMPTA,IA_US_RECHERCHE
0,Ens,Ens,172345,10142,4007,2204,1880,2508,4569,3438,887,7154,1765,2022,1116,351,2216,3096,2375
1,po1,Ens,94858,4004,1685,768,738,918,1396,1201,189,2509,516,711,304,60,598,1118,699
2,po2,Ens,50237,2839,1085,803,524,710,1348,969,247,2001,553,571,381,63,383,913,741
3,po3,Ens,22321,2267,833,364,377,594,1248,778,263,1771,448,444,273,100,669,804,628
4,po4,Ens,4929,1032,404,270,241,286,577,489,189,873,248,296,158,128,566,261,308

In [6]:
df_cloud.head()

,Taille_IR,ACT_IR,NB_ENT,CLOUD,COURRIEL,LOGICIELS,COMPTA,CLOUD_ERP,REL_CLIENT,CLOUD_SECU,BASES,STOCKAGE,CALCUL,CLOUD_PAAS,CLOUD_BASIC,CLOUD_INTERM,CLOUD_AVANCE
0,Ens,Ens,172345,46118,39626,31424,24789,15145,12791,26617,19487,34664,14309,11811,6307,6991,32559
1,po1,Ens,94858,19389,15899,12474,10023,5554,4444,10180,7575,14711,5529,3764,2932,3507,12832
2,po2,Ens,50237,14208,12463,9718,7895,4826,3505,7833,6315,10673,4409,3613,2192,2070,9854
3,po3,Ens,22321,9206,8258,6555,5022,3362,3235,6135,3875,6679,2966,2815,955,1178,7047
4,po4,Ens,4929,3314,3005,2677,1849,1402,1607,2470,1722,2602,1405,1619,228,235,2826

In [7]:
df_ia.head()

,Taille_IR,ACT_IR,NB_ENT,IA_TECH,IA_TECH_TEXMIN,IA_TECH_PAROLE,IA_TECH_GAT,IA_TECH_IMAGES,IA_TECH_AAAD,IA_TECH_DECIS,IA_TECH_MVT,IA_US,IA_US_MARKETING,IA_US_PRODUCT,IA_US_ADMIN,IA_US_LOGISTIQ,IA_US_SECU,IA_US_COMPTA,IA_US_RECHERCHE
0,Ens,Ens,172345,10142,4007,2204,1880,2508,4569,3438,887,7154,1765,2022,1116,351,2216,3096,2375
1,po1,Ens,94858,4004,1685,768,738,918,1396,1201,189,2509,516,711,304,60,598,1118,699
2,po2,Ens,50237,2839,1085,803,524,710,1348,969,247,2001,553,571,381,63,383,913,741
3,po3,Ens,22321,2267,833,364,377,594,1248,778,263,1771,448,444,273,100,669,804,628
4,po4,Ens,4929,1032,404,270,241,286,577,489,189,873,248,296,158,128,566,261,308